let STORE=null,user="";
const demoProducts=[{id:1,name:"منتج تجريبي 1",barcode:"100001",price:10,stock:25},{id:2,name:"منتج تجريبي 2",barcode:"100002",price:25,stock:12},{id:3,name:"منتج تجريبي 3",barcode:"100003",price:50,stock:8}];let cart=[];
async function loadPersistentStore(){if(window.omarpos){STORE=await window.omarpos.getStore();if(STORE.products?.length){demoProducts.length=0;STORE.products.forEach(p=>demoProducts.push(p))}}}loadPersistentStore();
const pages={home:{title:"الرئيسية",html:`<div class="stats"><div class="stat"><b>0 د.ل</b><small>مبيعات اليوم</small></div><div class="stat"><b>0</b><small>فواتير اليوم</small></div><div class="stat"><b>0</b><small>منتجات منخفضة</small></div><div class="stat"><b>0 د.ل</b><small>صافي اليوم</small></div></div><div class="section"><h2>الوصول السريع</h2><div class="tiles"><button class="tile green" onclick="newInvoice()"><span class="ico">🧾</span><b>فاتورة مبيعات</b><small>إصدار فاتورة جديدة</small></button><button class="tile blue" onclick="showProducts()"><span class="ico">📦</span><b>المنتجات</b><small>إدارة المخزون</small></button><button class="tile orange" onclick="page('customers')"><span class="ico">👥</span><b>العملاء</b><small>بيانات العملاء</small></button><button class="tile purple" onclick="page('reports')"><span class="ico">📊</span><b>التقارير</b><small>المبيعات والأرباح</small></button><button class="tile gray" onclick="page('settings')"><span class="ico">⚙</span><b>الإعدادات</b><small>إعدادات النظام</small></button></div></div>`},sales:{title:"المبيعات",html:`<div class="section"><h2>قائمة المبيعات</h2><button class="primary" onclick="newInvoice()">＋ فاتورة مبيعات جديدة</button><div class="empty">لا توجد فواتير حتى الآن.</div></div>`},customers:{title:"العملاء والمالية",html:`<div class="section"><h2>العملاء</h2><button class="primary" onclick="alert('سيتم إضافة إدارة العملاء في المرحلة التالية')">＋ إضافة عميل</button><div class="empty">لا توجد بيانات عملاء حتى الآن.</div></div>`},reports:{title:"التقارير",html:`<div class="stats"><div class="stat"><b>0 د.ل</b><small>إجمالي المبيعات</small></div><div class="stat"><b>0 د.ل</b><small>الأرباح</small></div><div class="stat"><b>0 د.ل</b><small>المصروفات</small></div><div class="stat"><b>0</b><small>الفواتير</small></div></div><div class="section"><h2>التقارير</h2><div class="empty">سيتم تفعيل التقارير التفصيلية مع قاعدة البيانات.</div></div>`},settings:{title:"الإعدادات والنظام",html:`<div class="section"><h2>إعدادات OmarPOS</h2><p>اسم المحل: مركز المهندس</p><p>المالك: عمر جمعه</p><p>الهاتف: 0923487251</p><button class="primary" onclick="openActivation()">🔑 الاشتراك والتفعيل</button><button class="secondary" onclick="showSystemInfo()">💾 مكان بيانات البرنامج</button></div>`}};
function chooseUser(u){user=u;document.getElementById('pinBox').classList.remove('hidden');document.getElementById('pin').focus()}
async function login(){const password=document.getElementById('pin').value;try{const r=await window.omarpos.licenseLogin({username:user,password}),s=r.data?.subscription;if(r.status===200&&s?.active){document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('userCard').innerHTML=`👤 <b>${s.username}</b><small>● الاشتراك: ${s.endAt?new Date(s.endAt).toLocaleDateString('ar-LY'):"مدى الحياة"}</small>`;page('home')}else if(r.status===200&&s?.status==='suspended')alert('هذا الحساب موقوف من الإدارة.');else if(r.status===200&&s?.expired)alert('انتهى الاشتراك. يرجى التجديد.');else alert('بيانات الدخول غير صحيحة أو خادم الترخيص غير متاح.')}catch(e){alert('تعذر الاتصال بخادم الترخيص. تأكد من إعداد OMARPOS_LICENSE_URL.')}}
function page(p){document.getElementById('title').textContent=pages[p].title;document.getElementById('content').innerHTML=pages[p].html;document.querySelectorAll('nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p))}
function logout(){location.reload()}
function openActivation(){document.getElementById('modal').innerHTML=`<div class="modal-box"><h2>🔑 اشتراك OmarPOS</h2><div class="plans"><div class="plan">🎁<b>7 أيام</b><small>تجريبي</small></div><div class="plan">📅<b>شهري / سنوي</b><small>حسب الاشتراك</small></div><div class="plan">♾️<b>مدى الحياة</b><small>بدون انتهاء</small></div></div><p>إدارة التفعيل تتم من لوحة الإدارة المركزية.</p><button class="secondary" onclick="closeModal()">إغلاق</button></div>`;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function money(n){return Number(n).toFixed(2)+" د.ل"}
function newInvoice(){document.getElementById('title').textContent='فاتورة مبيعات جديدة';document.getElementById('content').innerHTML=`<div class="pos-grid"><div class="section"><div class="pos-head"><h2>المنتجات</h2><input id="productSearch" placeholder="🔎 بحث بالاسم أو الباركود" oninput="renderProducts()"></div><div id="productList" class="product-list"></div></div><div class="section cart-panel"><h2>🛒 السلة</h2><div id="cartList"></div><div class="totals"><div>الإجمالي <b id="cartTotal">0.00 د.ل</b></div><div>الخصم <input id="discount" type="number" min="0" value="0" oninput="renderCart()"></div><div class="grand">الصافي <b id="grandTotal">0.00 د.ل</b></div></div><button class="primary" onclick="completeSale()">💳 إتمام البيع</button><button class="secondary" onclick="page('home')">إلغاء</button></div></div>`;renderProducts();renderCart()}
function renderProducts(){const q=(document.getElementById('productSearch')?.value||'').toLowerCase();const list=demoProducts.filter(p=>p.name.toLowerCase().includes(q)||String(p.barcode).includes(q));document.getElementById('productList').innerHTML=list.map(p=>`<button class="product" onclick="addToCart(${p.id})"><span>📦</span><div><b>${p.name}</b><small>باركود: ${p.barcode} • المخزون: ${p.stock}</small></div><strong>${money(p.price)}</strong></button>`).join('')||'<div class="empty">لا توجد منتجات</div>'}
function addToCart(id){const p=demoProducts.find(x=>x.id===id),r=cart.find(x=>x.id===id);if(r)r.qty++;else cart.push({...p,qty:1});renderCart()}
function changeQty(id,d){const r=cart.find(x=>x.id===id);if(!r)return;r.qty+=d;if(r.qty<=0)cart=cart.filter(x=>x.id!==id);renderCart()}
function renderCart(){const el=document.getElementById('cartList');if(!el)return;el.innerHTML=cart.length?cart.map(r=>`<div class="cart-row"><div><b>${r.name}</b><small>${money(r.price)} × ${r.qty}</small></div><div><button onclick="changeQty(${r.id},-1)">−</button><b>${r.qty}</b><button onclick="changeQty(${r.id},1)">+</button></div><strong>${money(r.price*r.qty)}</strong></div>`).join(''):'<div class="empty">السلة فارغة</div>';const total=cart.reduce((s,r)=>s+r.price*r.qty,0),d=Math.max(0,Number(document.getElementById('discount')?.value||0));document.getElementById('cartTotal').textContent=money(total);document.getElementById('grandTotal').textContent=money(Math.max(0,total-d))}
async function completeSale(){if(!cart.length)return alert('أضف منتجاً إلى الفاتورة أولاً');const d=Number(document.getElementById('discount').value||0),total=cart.reduce((s,r)=>s+r.price*r.qty,0);if(window.omarpos)await window.omarpos.addSale({items:cart.map(r=>({id:r.id,qty:r.qty,price:r.price})),total:Math.max(0,total-d),discount:d});alert('تم حفظ الفاتورة بقيمة '+money(Math.max(0,total-d)));cart=[];page('home')}
function showProducts(){document.getElementById('title').textContent='المنتجات والمخزون';document.getElementById('content').innerHTML=`<div class="section"><div class="pos-head"><h2>إدارة المنتجات</h2></div><table class="table"><thead><tr><th>المنتج</th><th>الباركود</th><th>السعر</th><th>المخزون</th></tr></thead><tbody>${demoProducts.map(p=>`<tr><td>${p.name}</td><td dir="ltr">${p.barcode}</td><td>${money(p.price)}</td><td>${p.stock}</td></tr>`).join('')}</tbody></table></div>`}
async function showSystemInfo(){const p=window.omarpos?await window.omarpos.dataPath():'غير متاح';alert('بيانات OmarPOS محفوظة محلياً على Windows:\n'+p)}
document.querySelectorAll('nav button[data-page]').forEach(b=>b.onclick=()=>b.dataset.page==='products'?showProducts():page(b.dataset.page));setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleString('ar-LY'),1000);
