let STORE=null,user="",role="";
const demoProducts=[{id:1,name:"منتج تجريبي 1",barcode:"100001",price:10,stock:25},{id:2,name:"منتج تجريبي 2",barcode:"100002",price:25,stock:12},{id:3,name:"منتج تجريبي 3",barcode:"100003",price:50,stock:8}];
let cart=[];
async function loadPersistentStore(){if(window.omarpos){STORE=await window.omarpos.getStore();if(!STORE.products)STORE.products=[];if(!STORE.sales)STORE.sales=[];demoProducts.length=0;STORE.products.forEach(p=>demoProducts.push(p));}}
loadPersistentStore();
const pages={
home:{title:"الرئيسية",html:`<div class="stats"><div class="stat"><b id="todaySales">0 د.ل</b><small>مبيعات اليوم</small></div><div class="stat"><b id="todayInvoices">0</b><small>فواتير اليوم</small></div><div class="stat"><b id="lowProducts">0</b><small>منتجات منخفضة</small></div><div class="stat"><b id="todayNet">0 د.ل</b><small>صافي اليوم</small></div></div><div class="section"><h2>الوصول السريع</h2><div class="tiles"><button class="tile green" onclick="newInvoice()"><span class="ico">🧾</span><b>فاتورة مبيعات</b><small>إصدار فاتورة جديدة</small></button><button class="tile blue" onclick="showProducts()"><span class="ico">📦</span><b>المنتجات</b><small>إدارة المخزون</small></button><button class="tile orange" onclick="page('customers')"><span class="ico">👥</span><b>العملاء</b><small>بيانات العملاء</small></button><button class="tile purple" onclick="page('reports')"><span class="ico">📊</span><b>التقارير</b><small>المبيعات والأرباح</small></button><button class="tile gray" onclick="page('settings')"><span class="ico">⚙</span><b>الإعدادات</b><small>إعدادات النظام</small></button></div></div>`},
sales:{title:"المبيعات",html:`<div class="section"><h2>قائمة المبيعات</h2><button class="primary" onclick="newInvoice()">＋ فاتورة مبيعات جديدة</button><div id="salesList"></div></div>`},
customers:{title:"العملاء والمالية",html:`<div class="section"><h2>العملاء</h2><div class="empty">سيتم تفعيل إدارة العملاء في المرحلة التالية.</div></div>`},
reports:{title:"التقارير",html:`<div class="section"><h2>التقارير</h2><div id="reportContent"></div></div>`},
settings:{title:"الإعدادات والنظام",html:`<div class="section"><h2>إعدادات OmarPOS</h2><p>اسم المحل: مركز المهندس</p><p>المالك: عمر جمعه</p><p>الهاتف: 0923487251</p><button class="primary" onclick="openActivation()">🔑 الاشتراك والتفعيل</button><button class="secondary" onclick="showSystemInfo()">💾 مكان بيانات البرنامج</button></div>`}
};
function chooseUser(r){role=r;document.getElementById('pinBox').classList.remove('hidden');document.getElementById('licenseUser')?.focus()}
async function login(){const password=document.getElementById('pin').value;const username=document.getElementById('licenseUser').value.trim();if(!username||!password)return alert('أدخل اسم المستخدم وكلمة المرور.');try{const r=await window.omarpos.licenseLogin({username,password}),s=r.data?.subscription;if(r.status===200&&s?.active){user=s.username;document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('userCard').innerHTML=`👤 <b>${s.username}</b><small>● ${role||'المستخدم'} • الاشتراك: ${s.endAt?new Date(s.endAt).toLocaleDateString('ar-LY'):"مدى الحياة"}</small>`;await loadPersistentStore();page('home')}else if(r.status===401)alert('اسم المستخدم أو كلمة المرور غير صحيحة.');else if(r.status===200&&s?.status==='suspended')alert('هذا الحساب موقوف من الإدارة.');else if(r.status===200&&s?.expired)alert('انتهى الاشتراك. يرجى التجديد.');else if(r.status>=500)alert('خادم الترخيص يواجه خطأ مؤقتاً. حاول مرة أخرى.');else alert('تعذر التحقق من الاشتراك.');}catch(e){alert('تعذر الاتصال بخادم الترخيص. تأكد من اتصال الإنترنت.')}}
function page(p){document.getElementById('title').textContent=pages[p].title;document.getElementById('content').innerHTML=pages[p].html;document.querySelectorAll('nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='home')refreshHome();if(p==='sales')renderSales();if(p==='reports')renderReports()}
function logout(){location.reload()}
function openActivation(){document.getElementById('modal').innerHTML=`<div class="modal-box"><h2>🔑 اشتراك OmarPOS</h2><div class="plans"><div class="plan">🎁<b>7 أيام</b><small>تجريبي</small></div><div class="plan">📅<b>شهري / سنوي</b><small>حسب الاشتراك</small></div><div class="plan">♾️<b>مدى الحياة</b><small>بدون انتهاء</small></div></div><p>إدارة التفعيل تتم من لوحة الإدارة المركزية.</p><button class="secondary" onclick="closeModal()">إغلاق</button></div>`;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function money(n){return Number(n||0).toFixed(2)+" د.ل"}
function todaySales(){const day=new Date().toDateString();return (STORE?.sales||[]).filter(s=>new Date(s.date).toDateString()===day)}
function refreshHome(){const s=todaySales(),total=s.reduce((a,x)=>a+Number(x.total||0),0),low=demoProducts.filter(p=>Number(p.stock)<=5).length;document.getElementById('todaySales')&&(document.getElementById('todaySales').textContent=money(total));document.getElementById('todayInvoices')&&(document.getElementById('todayInvoices').textContent=s.length);document.getElementById('lowProducts')&&(document.getElementById('lowProducts').textContent=low);document.getElementById('todayNet')&&(document.getElementById('todayNet').textContent=money(total))}
function newInvoice(){cart=[];document.getElementById('title').textContent='فاتورة مبيعات جديدة';document.getElementById('content').innerHTML=`<div class="pos-grid"><div class="section"><div class="pos-head"><h2>المنتجات</h2><input id="productSearch" placeholder="🔎 بحث بالاسم أو الباركود" oninput="renderProductsForSale()"></div><div id="productList" class="product-list"></div></div><div class="section cart-panel"><h2>🛒 السلة</h2><div id="cartList"></div><div class="totals"><div>الإجمالي <b id="cartTotal">0.00 د.ل</b></div><div>الخصم <input id="discount" type="number" min="0" value="0" oninput="renderCart()"></div><div class="grand">الصافي <b id="grandTotal">0.00 د.ل</b></div></div><button class="primary" onclick="completeSale()">💳 إتمام البيع</button><button class="secondary" onclick="page('home')">إلغاء</button></div></div>`;renderProductsForSale();renderCart()}
function renderProductsForSale(){const q=(document.getElementById('productSearch')?.value||'').toLowerCase();const list=demoProducts.filter(p=>p.name.toLowerCase().includes(q)||String(p.barcode).includes(q));document.getElementById('productList').innerHTML=list.map(p=>`<button class="product" onclick="addToCart(${p.id})"><span>📦</span><div><b>${p.name}</b><small>باركود: ${p.barcode} • المخزون: ${p.stock}</small></div><strong>${money(p.price)}</strong></button>`).join('')||'<div class="empty">لا توجد منتجات</div>'}
function addToCart(id){const p=demoProducts.find(x=>x.id===id);if(!p)return;if(p.stock<=0)return alert('هذا المنتج غير متوفر في المخزون.');const r=cart.find(x=>x.id===id);if(r&&r.qty>=p.stock)return alert('لا يمكن تجاوز كمية المخزون.');if(r)r.qty++;else cart.push({...p,qty:1});renderCart()}
function changeQty(id,d){const r=cart.find(x=>x.id===id);if(!r)return;const p=demoProducts.find(x=>x.id===id);r.qty+=d;if(p&&r.qty>p.stock)r.qty=p.stock;if(r.qty<=0)cart=cart.filter(x=>x.id!==id);renderCart()}
function renderCart(){const el=document.getElementById('cartList');if(!el)return;el.innerHTML=cart.length?cart.map(r=>`<div class="cart-row"><div><b>${r.name}</b><small>${money(r.price)} × ${r.qty}</small></div><div><button onclick="changeQty(${r.id},-1)">−</button><b>${r.qty}</b><button onclick="changeQty(${r.id},1)">+</button></div><strong>${money(r.price*r.qty)}</strong></div>`).join(''):'<div class="empty">السلة فارغة</div>';const total=cart.reduce((s,r)=>s+r.price*r.qty,0),d=Math.max(0,Number(document.getElementById('discount')?.value||0));document.getElementById('cartTotal').textContent=money(total);document.getElementById('grandTotal').textContent=money(Math.max(0,total-d))}
async function completeSale(){if(!cart.length)return alert('أضف منتجاً إلى الفاتورة أولاً');const d=Math.max(0,Number(document.getElementById('discount').value||0)),total=cart.reduce((s,r)=>s+r.price*r.qty,0),finalTotal=Math.max(0,total-d);if(d>total)return alert('الخصم لا يمكن أن يكون أكبر من الإجمالي.');const sale={items:cart.map(r=>({id:r.id,name:r.name,qty:r.qty,price:r.price})),total:finalTotal,discount:d};try{let saved={...sale,id:Date.now(),date:new Date().toISOString()};if(window.omarpos){saved=await window.omarpos.addSale(sale);STORE=await window.omarpos.getStore();demoProducts.length=0;STORE.products.forEach(p=>demoProducts.push(p))}else{if(!STORE)STORE={products:demoProducts,sales:[]};STORE.sales.push(saved)};const invoice=saved;cart=[];showInvoice(invoice)}catch(e){alert('تعذر حفظ الفاتورة: '+e.message)}}
function showInvoice(sale){const items=(sale.items||[]).map(i=>`<tr><td>${i.name||('منتج #'+i.id)}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(Number(i.price)*Number(i.qty))}</td></tr>`).join('');document.getElementById('modal').innerHTML=`<div class="modal-box invoice"><h2>🧾 فاتورة OmarPOS</h2><p>مركز المهندس</p><p>رقم الفاتورة: <b>${sale.id}</b><br>التاريخ: ${new Date(sale.date).toLocaleString('ar-LY')}</p><table class="table"><thead><tr><th>الصنف</th><th>الكمية</th><th>السعر</th><th>الإجمالي</th></tr></thead><tbody>${items}</tbody></table><div class="totals"><div>الخصم: <b>${money(sale.discount)}</b></div><div class="grand">الإجمالي النهائي: <b>${money(sale.total)}</b></div></div><button class="primary" onclick="printInvoice()">🖨 طباعة الفاتورة</button><button class="secondary" onclick="closeInvoice()">إغلاق</button></div>`;document.getElementById('modal').classList.remove('hidden')}
function printInvoice(){window.print()}
function closeInvoice(){closeModal();page('home')}
function showProducts(){document.getElementById('title').textContent='المنتجات والمخزون';document.getElementById('content').innerHTML=`<div class="section"><div class="pos-head"><h2>إدارة المنتجات</h2><button class="primary" onclick="openProductForm()">＋ إضافة صنف جديد</button></div><div id="productTable"></div></div>`;renderProductTable()}
function renderProductTable(){const el=document.getElementById('productTable');if(!el)return;el.innerHTML=demoProducts.length?`<table class="table"><thead><tr><th>الصنف</th><th>الباركود</th><th>السعر</th><th>المخزون</th><th>الإجراءات</th></tr></thead><tbody>${demoProducts.map(p=>`<tr><td>${p.name}</td><td dir="ltr">${p.barcode||''}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button class="secondary" onclick="openProductForm(${p.id})">تعديل</button> <button class="secondary" onclick="deleteProduct(${p.id})">حذف</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">لا توجد أصناف. اضغط «إضافة صنف جديد» للبدء.</div>'}
function openProductForm(id){const p=id?demoProducts.find(x=>x.id===id):null;document.getElementById('modal').innerHTML=`<div class="modal-box"><h2>${p?'✏️ تعديل الصنف':'📦 إضافة صنف جديد'}</h2><label>اسم الصنف<input id="pfName" value="${p?.name||''}" placeholder="مثال: مياه معدنية"></label><label>الباركود<input id="pfBarcode" value="${p?.barcode||''}" placeholder="اختياري"></label><label>السعر<input id="pfPrice" type="number" min="0" step="0.01" value="${p?.price??''}"></label><label>المخزون<input id="pfStock" type="number" min="0" step="1" value="${p?.stock??0}"></label><button class="primary" onclick="saveProduct(${id||0})">💾 حفظ الصنف</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>`;document.getElementById('modal').classList.remove('hidden')}
async function saveProduct(id){const name=document.getElementById('pfName').value.trim(),barcode=document.getElementById('pfBarcode').value.trim(),price=Number(document.getElementById('pfPrice').value),stock=Number(document.getElementById('pfStock').value);if(!name)return alert('أدخل اسم الصنف.');if(!Number.isFinite(price)||price<0)return alert('أدخل سعراً صحيحاً.');if(!Number.isInteger(stock)||stock<0)return alert('أدخل مخزوناً صحيحاً.');if(barcode&&demoProducts.some(p=>String(p.barcode)===barcode&&p.id!==id))return alert('هذا الباركود مستخدم لصنف آخر.');if(id){const p=demoProducts.find(x=>x.id===id);if(p)Object.assign(p,{name,barcode,price,stock})}else{const newId=demoProducts.reduce((m,p)=>Math.max(m,Number(p.id)||0),0)+1;demoProducts.push({id:newId,name,barcode,price,stock})}if(window.omarpos){STORE=await window.omarpos.getStore();STORE.products=demoProducts;await window.omarpos.saveStore(STORE);STORE=await window.omarpos.getStore()}closeModal();showProducts()}
async function deleteProduct(id){const p=demoProducts.find(x=>x.id===id);if(!p)return;if(!confirm('حذف الصنف «'+p.name+'»؟'))return;demoProducts.splice(demoProducts.findIndex(x=>x.id===id),1);if(window.omarpos){STORE=await window.omarpos.getStore();STORE.products=demoProducts;await window.omarpos.saveStore(STORE)}renderProductTable()}
function renderSales(){const el=document.getElementById('salesList');const sales=[...(STORE?.sales||[])].sort((a,b)=>new Date(b.date)-new Date(a.date));el.innerHTML=sales.length?`<table class="table"><thead><tr><th>رقم الفاتورة</th><th>التاريخ</th><th>الأصناف</th><th>الإجمالي</th><th></th></tr></thead><tbody>${sales.map(s=>`<tr><td>${s.id}</td><td>${new Date(s.date).toLocaleString('ar-LY')}</td><td>${(s.items||[]).reduce((a,i)=>a+Number(i.qty||0),0)}</td><td>${money(s.total)}</td><td><button class="secondary" onclick='showInvoice(${JSON.stringify(s).replace(/'/g,"&#39;")})'>عرض</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">لا توجد فواتير حتى الآن.</div>'}
function renderReports(){const sales=STORE?.sales||[],total=sales.reduce((a,s)=>a+Number(s.total||0),0);document.getElementById('reportContent').innerHTML=`<div class="stats"><div class="stat"><b>${money(total)}</b><small>إجمالي المبيعات</small></div><div class="stat"><b>${sales.length}</b><small>عدد الفواتير</small></div><div class="stat"><b>${demoProducts.length}</b><small>عدد الأصناف</small></div><div class="stat"><b>${demoProducts.reduce((a,p)=>a+Number(p.stock||0),0)}</b><small>إجمالي المخزون</small></div></div>`}
async function showSystemInfo(){const p=window.omarpos?await window.omarpos.dataPath():'غير متاح';alert('بيانات OmarPOS محفوظة محلياً على Windows:\n'+p)}
document.querySelectorAll('nav button[data-page]').forEach(b=>b.onclick=()=>b.dataset.page==='products'?showProducts():page(b.dataset.page));
setInterval(()=>{const c=document.getElementById('clock');if(c)c.textContent=new Date().toLocaleString('ar-LY')},1000);
