// OmarPOS - functional modules and production UI
(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localKey='omarpos_store_v1';
function shape(s){s=s&&typeof s==='object'?s:{};['products','sales','customers','suppliers','purchases','expenses','returns','accounts','receipts','payments'].forEach(k=>{if(!Array.isArray(s[k]))s[k]=[]});return s}
function sync(s){STORE=shape(s);demoProducts.length=0;STORE.products.forEach(p=>{p.price=Number(p.price||0);p.minPrice=Number(p.minPrice??0);p.costPrice=Number(p.costPrice??0);p.stock=Number(p.stock||0);demoProducts.push(p)});return STORE}
async function fresh(){return sync(await window.omarpos.getStore())}
async function save(s){s=shape(s);await window.omarpos.saveStore(s);return sync(s)}
function next(a){return a.reduce((m,x)=>Math.max(m,Number(x.id)||0),0)+1}
function field(id){return document.getElementById(id)}
function modal(html){openModal(html)}
function module(title,body){field('title').textContent=title;field('content').innerHTML=body}
function table(headers,rows,empty='لا توجد بيانات.'){return rows.length?'<div style="overflow:auto"><table class="table"><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>':'<div class="empty">'+empty+'</div>'}

window.saveProduct=async function(id){
 const name=(field('pfName')?.value||'').trim(),barcode=(field('pfBarcode')?.value||'').trim(),price=Number(field('pfPrice')?.value),minPrice=Number(field('pfMinPrice')?.value||0),costPrice=Number(field('pfCostPrice')?.value||0),stock=Number(field('pfStock')?.value);
 if(!name)return alert('أدخل اسم الصنف.');
 if(!Number.isFinite(price)||price<0)return alert('أدخل سعر بيع صحيح.');
 if(!Number.isFinite(minPrice)||minPrice<0||minPrice>price)return alert('أقل سعر للبيع يجب أن يكون بين 0 وسعر البيع.');
 if(!Number.isFinite(costPrice)||costPrice<0)return alert('أدخل سعر شراء صحيح.');
 if(!Number.isInteger(stock)||stock<0)return alert('أدخل كمية صحيحة.');
 const s=await fresh(); if(barcode&&s.products.some(p=>String(p.barcode||'')===barcode&&Number(p.id)!==Number(id)))return alert('هذا الباركود مستخدم لصنف آخر.');
 let p=id?s.products.find(x=>Number(x.id)===Number(id)):null;
 if(p)Object.assign(p,{name,barcode,price,minPrice,costPrice,stock});else s.products.push({id:next(s.products),name,barcode,price,minPrice,costPrice,stock});
 await save(s);closeModal();showProducts()
};
window.openProductForm=function(id){
 const p=id?demoProducts.find(x=>Number(x.id)===Number(id)):null;
 modal('<div class="modal-box"><h2>'+(p?'تعديل الصنف':'إضافة صنف')+'</h2>'+
 '<label>اسم الصنف<input id="pfName" value="'+esc(p?.name)+'"></label>'+
 '<label>الباركود<input id="pfBarcode" value="'+esc(p?.barcode)+'"></label>'+
 '<label>سعر البيع<input id="pfPrice" type="number" min="0" step="0.01" value="'+(p?.price??'')+'"></label>'+
 '<label>أقل سعر للبيع<input id="pfMinPrice" type="number" min="0" step="0.01" value="'+(p?.minPrice??0)+'"></label>'+
 '<label>سعر الشراء<input id="pfCostPrice" type="number" min="0" step="0.01" value="'+(p?.costPrice??0)+'"></label>'+
 '<label>المخزون<input id="pfStock" type="number" min="0" step="1" value="'+(p?.stock??0)+'"></label>'+
 '<button class="primary" onclick="saveProduct('+(id||0)+')">💾 حفظ</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>')
};
window.showProducts=function(){
 module('المنتجات والمخزون','<div class="section"><div class="pos-head"><h2>إدارة المنتجات</h2><button class="primary" onclick="openProductForm()">＋ إضافة صنف</button></div><input id="prodQ" placeholder="🔎 بحث بالاسم أو الباركود" style="width:100%;padding:12px;background:#06111a;color:#fff;border:1px solid #15354b;border-radius:9px" oninput="renderProductTable()"><div id="productTable"></div></div>');renderProductTable()
};
window.renderProductTable=function(){
 const q=(field('prodQ')?.value||'').toLowerCase();const a=demoProducts.filter(p=>String(p.name).toLowerCase().includes(q)||String(p.barcode||'').includes(q));
 field('productTable').innerHTML=table(['الصنف','الباركود','سعر الشراء','سعر البيع','أقل سعر','المخزون','إجراء'],a.map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+esc(p.barcode)+'</td><td>'+money(p.costPrice)+'</td><td>'+money(p.price)+'</td><td>'+money(p.minPrice)+'</td><td>'+p.stock+'</td><td><button class="secondary" onclick="openProductForm('+p.id+')">تعديل</button> <button class="secondary" onclick="deleteProduct('+p.id+')">حذف</button></td></tr>'))
};
window.deleteProduct=async function(id){const s=await fresh(),p=s.products.find(x=>Number(x.id)===Number(id));if(!p)return;if(!confirm('حذف الصنف «'+p.name+'»؟'))return;s.products=s.products.filter(x=>Number(x.id)!==Number(id));await save(s);showProducts()};

function salePriceOk(r){return Number(r.price)>=Number(r.minPrice||0)}
window.newInvoice=function(){
 cart=[];
 module('فاتورة مبيعات جديدة','<div class="pos-grid"><div class="section"><div class="pos-head"><h2>المنتجات</h2><input id="productSearch" placeholder="🔎 الاسم أو امسح الباركود ثم Enter" oninput="renderProductsForSale()" onkeydown="barcodeEnter(event)"></div><div id="productList" class="product-list"></div></div><div class="section"><h2>🛒 السلة</h2><div id="cartList"></div><div class="totals"><div>الإجمالي <b id="cartTotal">0.00 د.ل</b></div><div>الخصم <input id="discount" type="number" min="0" value="0" oninput="renderCart()"></div><div class="grand">الصافي <b id="grandTotal">0.00 د.ل</b></div></div><button class="primary" onclick="completeSale()">💳 إتمام البيع</button><button class="secondary" onclick="page('home')">إلغاء</button></div></div>');
 renderProductsForSale();renderCart();field('productSearch')?.focus()
};
window.barcodeEnter=function(e){if(e.key!=='Enter')return;e.preventDefault();const q=field('productSearch').value.trim();if(!q)return;const p=demoProducts.find(x=>String(x.barcode||'')===q);if(p){addToCart(p.id);field('productSearch').value='';renderProductsForSale()}else alert('لم يتم العثور على صنف بهذا الباركود.')};
window.renderProductsForSale=function(){const q=(field('productSearch')?.value||'').trim().toLowerCase(),a=demoProducts.filter(p=>String(p.name).toLowerCase().includes(q)||String(p.barcode||'').toLowerCase().includes(q));field('productList').innerHTML=a.map(p=>'<button class="product" onclick="addToCart('+p.id+')"><span>📦</span><div><b>'+esc(p.name)+'</b><small>باركود: '+esc(p.barcode||'-')+' • مخزون: '+p.stock+' • أقل سعر: '+money(p.minPrice)+'</small></div><strong>'+money(p.price)+'</strong></button>').join('')||'<div class="empty">لا توجد منتجات</div>'};
window.addToCart=function(id){const p=demoProducts.find(x=>Number(x.id)===Number(id));if(!p)return;if(p.stock<=0)return alert('المخزون غير متوفر.');let r=cart.find(x=>Number(x.id)===Number(id));if(r&&r.qty>=p.stock)return alert('لا يمكن تجاوز المخزون.');if(r)r.qty++;else cart.push({...p,qty:1,price:Number(p.price)});renderCart()};
window.changeQty=function(id,d){const r=cart.find(x=>Number(x.id)===Number(id));if(!r)return;const p=demoProducts.find(x=>Number(x.id)===Number(id));r.qty+=d;if(r.qty>p.stock)r.qty=p.stock;if(r.qty<=0)cart=cart.filter(x=>x.id!==id);renderCart()};
window.setCartPrice=function(id,v){const r=cart.find(x=>Number(x.id)===Number(id));if(!r)return;const n=Number(v),p=demoProducts.find(x=>Number(x.id)===Number(id));if(!Number.isFinite(n)||n<Number(p.minPrice||0)){alert('لا يمكن البيع بأقل من '+money(p.minPrice));r.price=p.price;renderCart();return}r.price=n;renderCart()};
window.renderCart=function(){const e=field('cartList');if(!e)return;e.innerHTML=cart.length?cart.map(r=>'<div class="cart-row"><div><b>'+esc(r.name)+'</b><small>أقل سعر: '+money(r.minPrice)+'</small></div><div><input type="number" min="'+Number(r.minPrice||0)+'" step="0.01" value="'+Number(r.price).toFixed(2)+'" onchange="setCartPrice('+r.id+',this.value)" style="width:90px;background:#07111a;color:#fff;border:1px solid #15354b;padding:6px"> <button onclick="changeQty('+r.id+',-1)">−</button> '+r.qty+' <button onclick="changeQty('+r.id+',1)">+</button></div><strong>'+money(r.price*r.qty)+'</strong></div>').join(''):'<div class="empty">السلة فارغة</div>';const t=cart.reduce((a,r)=>a+r.price*r.qty,0),d=Math.max(0,Number(field('discount')?.value||0));field('cartTotal').textContent=money(t);field('grandTotal').textContent=money(Math.max(0,t-d))};
window.completeSale=async function(){if(!cart.length)return alert('أضف منتجاً أولاً.');for(const r of cart)if(!salePriceOk(r))return alert('سعر «'+r.name+'» أقل من الحد الأدنى للبيع.');const d=Math.max(0,Number(field('discount').value||0)),t=cart.reduce((a,r)=>a+r.price*r.qty,0);if(d>t)return alert('الخصم غير صحيح.');try{const s=await window.omarpos.addSale({items:cart.map(r=>({id:r.id,qty:r.qty,price:r.price,name:r.name})),total:t-d,discount:d});await fresh();cart=[];showInvoice(s)}catch(e){alert('تعذر إتمام البيع: '+e.message)}};

window.showInvoice=function(s){modal('<div class="modal-box invoice" id="invoicePrint"><h2>🧾 فاتورة OmarPOS</h2><p>مركز المهندس<br>رقم الفاتورة: <b>'+esc(s.id)+'</b><br>'+new Date(s.date).toLocaleString('ar-LY')+'</p>'+table(['الصنف','الكمية','السعر','الإجمالي'],s.items.map(i=>'<tr><td>'+esc(i.name)+'</td><td>'+i.qty+'</td><td>'+money(i.price)+'</td><td>'+money(i.price*i.qty)+'</td></tr>'))+'<div class="totals"><div>الخصم <b>'+money(s.discount)+'</b></div><div class="grand">الصافي <b>'+money(s.total)+'</b></div></div><button class="primary" onclick="printInvoice()">🖨 طباعة</button><button class="secondary" onclick="closeModal()">إغلاق</button></div>')};
window.printInvoice=function(){window.print()};

window.renderSales=function(){module('المبيعات','<div class="section"><div class="pos-head"><h2>فواتير المبيعات</h2><button class="primary" onclick="newInvoice()">＋ فاتورة جديدة</button></div><div id="salesList"></div></div>');const a=STORE.sales.slice().reverse();field('salesList').innerHTML=table(['رقم','التاريخ','الإجمالي','الإجراء'],a.map(s=>'<tr><td>'+s.id+'</td><td>'+new Date(s.date).toLocaleString('ar-LY')+'</td><td>'+money(s.total)+'</td><td><button class="secondary" onclick="showInvoice('+JSON.stringify(s).replace(/'/g,'&#39;')+')">عرض</button> <button class="secondary" onclick="deleteSale('+s.id+')">حذف</button> <button class="secondary" onclick="returnSale('+s.id+')">استرجاع</button></td></tr>'))};
window.deleteSale=async function(id){const s=STORE.sales.find(x=>Number(x.id)===Number(id));if(!s||!confirm('حذف الفاتورة وإعادة الكميات للمخزون؟'))return;for(const i of s.items||[]){const p=STORE.products.find(x=>Number(x.id)===Number(i.id));if(p)p.stock+=Number(i.qty||0)}STORE.sales=STORE.sales.filter(x=>Number(x.id)!==Number(id));await save(STORE);renderSales()};
window.returnSale=async function(id){const s=await fresh(),sale=s.sales.find(x=>Number(x.id)===Number(id));if(!sale)return;const already=s.returns.some(r=>Number(r.saleId)===Number(id)&&r.status==='completed');if(already)return alert('تم استرجاع هذه الفاتورة مسبقاً.');if(!confirm('استرجاع كامل الفاتورة رقم '+id+' وإعادة المنتجات للمخزون؟'))return;for(const i of sale.items||[]){const p=s.products.find(x=>Number(x.id)===Number(i.id));if(p)p.stock+=Number(i.qty||0)}s.returns.push({id:next(s.returns),saleId:id,items:sale.items,date:new Date().toISOString(),amount:sale.total,status:'completed'});await save(s);renderSales();alert('تم الاسترجاع وإعادة المخزون.')};

window.barcodeProducts=function(){module('باركود المنتجات','<div class="section"><h2>البحث بالباركود</h2><input id="barcodeQ" autofocus placeholder="امسح الباركود ثم اضغط Enter" style="width:100%;padding:14px;background:#06111a;color:#fff;border:1px solid #15354b;border-radius:9px" oninput="findBarcode()" onkeydown="barcodeModuleEnter(event)"><div id="barcodeResult"></div></div>');field('barcodeQ')?.focus()};
window.findBarcode=function(){const q=(field('barcodeQ')?.value||'').trim().toLowerCase(),a=q?demoProducts.filter(p=>String(p.barcode||'').toLowerCase().includes(q)||String(p.name).toLowerCase().includes(q)):[];field('barcodeResult').innerHTML=a.map(p=>'<div class="section"><h3>'+esc(p.name)+'</h3><p>الباركود: '+esc(p.barcode)+'<br>سعر البيع: '+money(p.price)+'<br>أقل سعر: '+money(p.minPrice)+'<br>المخزون: '+p.stock+'</p><button class="primary" onclick="newInvoice();setTimeout(()=>{field(\\'productSearch\\').value='+JSON.stringify(p.barcode)+';barcodeEnter({key:\\'Enter\\',preventDefault(){}})},0)">بيع هذا الصنف</button></div>').join('')||'<div class="empty">لم يتم العثور على الصنف.</div>'};
window.barcodeModuleEnter=function(e){if(e.key==='Enter'){const p=demoProducts.find(x=>String(x.barcode||'')===field('barcodeQ').value.trim());if(p){newInvoice();setTimeout(()=>addToCart(p.id),0)}else alert('الباركود غير موجود.')}};

function simpleHeader(title,add){return '<div class="section"><div class="pos-head"><h2>'+title+'</h2><button class="primary" onclick="'+add+'">＋ إضافة</button></div>'}
window.customers=function(){module('العملاء',simpleHeader('العملاء','openCustomerForm()')+'<div id="customerTable"></div></div>');renderCustomers()};
window.openCustomerForm=function(id){const c=id?STORE.customers.find(x=>Number(x.id)===Number(id)):null;modal('<div class="modal-box"><h2>'+(c?'تعديل عميل':'إضافة عميل')+'</h2><label>الاسم<input id="cfName" value="'+esc(c?.name)+'"></label><label>الهاتف<input id="cfPhone" value="'+esc(c?.phone)+'"></label><label>العنوان<input id="cfAddress" value="'+esc(c?.address)+'"></label><label>الرصيد<input id="cfBalance" type="number" step="0.01" value="'+(c?.balance??0)+'"></label><button class="primary" onclick="saveCustomer('+(id||0)+')">حفظ</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>')};
window.saveCustomer=async function(id){const s=await fresh(),name=(field('cfName').value||'').trim();if(!name)return alert('أدخل اسم العميل.');const c=id?s.customers.find(x=>Number(x.id)===Number(id)):null,d={name,phone:field('cfPhone').value.trim(),address:field('cfAddress').value.trim(),balance:Number(field('cfBalance').value||0)};if(c)Object.assign(c,d);else s.customers.push({id:next(s.customers),...d});await save(s);closeModal();customers()};
window.renderCustomers=function(){field('customerTable').innerHTML=table(['الاسم','الهاتف','العنوان','الرصيد','إجراء'],STORE.customers.map(c=>'<tr><td>'+esc(c.name)+'</td><td>'+esc(c.phone)+'</td><td>'+esc(c.address)+'</td><td>'+money(c.balance)+'</td><td><button class="secondary" onclick="openCustomerForm('+c.id+')">تعديل</button> <button class="secondary" onclick="deleteCustomer('+c.id+')">حذف</button></td></tr>'))};
window.deleteCustomer=async function(id){if(!confirm('حذف العميل؟'))return;const s=await fresh();s.customers=s.customers.filter(c=>Number(c.id)!==Number(id));await save(s);customers()};

window.suppliers=function(){module('الموردون',simpleHeader('الموردون','openSupplierForm()')+'<div id="supplierTable"></div></div>');renderSuppliers()};
window.openSupplierForm=function(id){const s=id?STORE.suppliers.find(x=>Number(x.id)===Number(id)):null;modal('<div class="modal-box"><h2>مورد</h2><label>الاسم<input id="sfName" value="'+esc(s?.name)+'"></label><label>الهاتف<input id="sfPhone" value="'+esc(s?.phone)+'"></label><label>العنوان<input id="sfAddress" value="'+esc(s?.address)+'"></label><button class="primary" onclick="saveSupplier('+(id||0)+')">حفظ</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>')};
window.saveSupplier=async function(id){const s=await fresh(),name=field('sfName').value.trim();if(!name)return alert('أدخل اسم المورد.');const old=id?s.suppliers.find(x=>Number(x.id)===Number(id)):null,d={name,phone:field('sfPhone').value.trim(),address:field('sfAddress').value.trim()};if(old)Object.assign(old,d);else s.suppliers.push({id:next(s.suppliers),...d});await save(s);closeModal();suppliers()};
window.renderSuppliers=function(){field('supplierTable').innerHTML=table(['الاسم','الهاتف','العنوان','إجراء'],STORE.suppliers.map(s=>'<tr><td>'+esc(s.name)+'</td><td>'+esc(s.phone)+'</td><td>'+esc(s.address)+'</td><td><button class="secondary" onclick="openSupplierForm('+s.id+')">تعديل</button> <button class="secondary" onclick="deleteSupplier('+s.id+')">حذف</button></td></tr>'))};
window.deleteSupplier=async function(id){const s=await fresh();s.suppliers=s.suppliers.filter(x=>Number(x.id)!==Number(id));await save(s);suppliers()};

window.purchases=function(){module('المشتريات',simpleHeader('المشتريات','openPurchaseForm()')+'<div id="purchaseTable"></div></div>');field('purchaseTable').innerHTML=table(['التاريخ','المورد','الصنف','الكمية','التكلفة','الإجمالي'],STORE.purchases.slice().reverse().map(p=>'<tr><td>'+new Date(p.date).toLocaleString('ar-LY')+'</td><td>'+esc(p.supplierName)+'</td><td>'+esc(p.productName)+'</td><td>'+p.qty+'</td><td>'+money(p.cost)+'</td><td>'+money(p.total)+'</td></tr>'))};
window.openPurchaseForm=function(){modal('<div class="modal-box"><h2>فاتورة مشتريات</h2><label>المورد<select id="buySupplier" style="width:100%;padding:10px;background:#06111a;color:#fff">'+STORE.suppliers.map(s=>'<option value="'+s.id+'">'+esc(s.name)+'</option>').join('')+'</select></label><label>الصنف<select id="buyProduct" style="width:100%;padding:10px;background:#06111a;color:#fff">'+demoProducts.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join('')+'</select></label><label>الكمية<input id="buyQty" type="number" min="1" value="1"></label><label>سعر الشراء<input id="buyCost" type="number" min="0" step="0.01" value="0"></label><button class="primary" onclick="savePurchase()">حفظ المشتريات وزيادة المخزون</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>')};
window.savePurchase=async function(){const s=await fresh(),p=s.products.find(x=>Number(x.id)===Number(field('buyProduct').value)),sup=s.suppliers.find(x=>Number(x.id)===Number(field('buySupplier').value)),qty=Number(field('buyQty').value),cost=Number(field('buyCost').value);if(!p||!sup||!Number.isInteger(qty)||qty<=0||!Number.isFinite(cost)||cost<0)return alert('بيانات المشتريات غير صحيحة.');p.stock+=qty;p.costPrice=cost;s.purchases.push({id:next(s.purchases),date:new Date().toISOString(),supplierId:sup.id,supplierName:sup.name,productId:p.id,productName:p.name,qty,cost,total:qty*cost});await save(s);closeModal();purchases()};

async function moneyRecord(kind,title,arrKey){module(title,simpleHeader(title,'openMoneyForm(\\''+kind+'\\')')+'<div id="moneyTable"></div></div>');const a=STORE[arrKey]||[];field('moneyTable').innerHTML=table(['التاريخ','البيان','المبلغ','إجراء'],a.slice().reverse().map(x=>'<tr><td>'+new Date(x.date).toLocaleString('ar-LY')+'</td><td>'+esc(x.name)+'</td><td>'+money(x.amount)+'</td><td><button class="secondary" onclick="removeMoney(\\''+arrKey+'\\','+x.id+')">حذف</button></td></tr>'))}
window.openMoneyForm=function(kind){modal('<div class="modal-box"><h2>إضافة</h2><label>البيان<input id="mfName"></label><label>المبلغ<input id="mfAmount" type="number" min="0" step="0.01"></label><label>ملاحظات<input id="mfNote"></label><button class="primary" onclick="saveMoney(\\''+kind+'\\')">حفظ</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>')};
window.saveMoney=async function(kind){const s=await fresh(),name=field('mfName').value.trim(),amount=Number(field('mfAmount').value||0);if(!name||!Number.isFinite(amount)||amount<=0)return alert('أدخل البيان والمبلغ.');const rec={id:next(s[kind]),date:new Date().toISOString(),name,amount,note:field('mfNote').value.trim(),type:kind};if(kind==='expense')s.expenses.push(rec);else if(kind==='payment')s.payments.push(rec);else s.receipts.push(rec);await save(s);closeModal();({expense:expenses,payment:payments,receipt:receipts}[kind])()};
window.removeMoney=async function(k,id){const s=await fresh();s[k]=s[k].filter(x=>Number(x.id)!==Number(id));await save(s);({expenses, payments, receipts}[k])()};
window.expenses=function(){moneyRecord('expense','المصروفات','expenses')};
window.payments=function(){moneyRecord('payment','سندات الصرف','payments')};
window.receipts=function(){moneyRecord('receipt','سندات القبض','receipts')};

window.inventory=function(){module('المخزون','<div class="section"><input id="invQ" placeholder="🔎 بحث" style="width:100%;padding:12px;background:#06111a;color:#fff;border:1px solid #15354b;border-radius:9px" oninput="renderInventory()"><div id="invTable"></div></div>');renderInventory()};
window.renderInventory=function(){const q=(field('invQ')?.value||'').toLowerCase(),a=demoProducts.filter(p=>String(p.name).toLowerCase().includes(q)||String(p.barcode||'').includes(q));field('invTable').innerHTML=table(['الصنف','الباركود','المخزون','القيمة بسعر الشراء','الحالة'],a.map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+esc(p.barcode)+'</td><td>'+p.stock+'</td><td>'+money(p.stock*p.costPrice)+'</td><td>'+(p.stock<=5?'منخفض':'متوفر')+'</td></tr>'))};
window.stocktake=function(){module('الجرد','<div class="section"><h2>الجرد الفعلي</h2><div id="stocktakeTable"></div></div>');field('stocktakeTable').innerHTML=table(['الصنف','الحالي','الجرد الفعلي','الفرق','حفظ'],demoProducts.map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+p.stock+'</td><td><input id="stk'+p.id+'" type="number" min="0" value="'+p.stock+'" style="width:100px"></td><td id="diff'+p.id+'">0</td><td><button class="secondary" onclick="saveStock('+p.id+')">حفظ</button></td></tr>'))};
window.saveStock=async function(id){const s=await fresh(),p=s.products.find(x=>Number(x.id)===Number(id)),v=Number(field('stk'+id).value);if(!p||!Number.isInteger(v)||v<0)return alert('الكمية غير صحيحة.');p.stock=v;await save(s);stocktake()};

window.accounts=function(){module('الحسابات','<div class="stats"><div class="stat"><b>'+money(STORE.receipts.reduce((a,x)=>a+x.amount,0))+'</b><small>سندات القبض</small></div><div class="stat"><b>'+money(STORE.payments.reduce((a,x)=>a+x.amount,0))+'</b><small>سندات الصرف</small></div><div class="stat"><b>'+money(STORE.expenses.reduce((a,x)=>a+x.amount,0))+'</b><small>المصروفات</small></div></div><div class="section"><h2>آخر العمليات</h2>'+table(['التاريخ','النوع','البيان','المبلغ'],[...STORE.receipts.map(x=>'<tr><td>'+x.date+'</td><td>قبض</td><td>'+esc(x.name)+'</td><td>'+money(x.amount)+'</td></tr>'),...STORE.payments.map(x=>'<tr><td>'+x.date+'</td><td>صرف</td><td>'+esc(x.name)+'</td><td>'+money(x.amount)+'</td></tr>')])+'</div>')};
window.profits=function(){let revenue=STORE.sales.reduce((a,s)=>a+Number(s.total||0),0),cost=0;STORE.sales.forEach(s=>(s.items||[]).forEach(i=>{const p=STORE.products.find(x=>Number(x.id)===Number(i.id));cost+=Number(p?.costPrice||0)*Number(i.qty||0)}));const exp=STORE.expenses.reduce((a,x)=>a+Number(x.amount||0),0);module('الأرباح','<div class="stats"><div class="stat"><b>'+money(revenue)+'</b><small>المبيعات</small></div><div class="stat"><b>'+money(cost)+'</b><small>تكلفة البضاعة</small></div><div class="stat"><b>'+money(exp)+'</b><small>المصروفات</small></div><div class="stat"><b>'+money(revenue-cost-exp)+'</b><small>صافي الربح</small></div></div>')};

window.salesReturns=function(){module('استرجاع المبيعات','<div class="section"><h2>فواتير قابلة للاسترجاع</h2><div id="returnsSales"></div></div>');const done=new Set(STORE.returns.filter(r=>r.status==='completed').map(r=>Number(r.saleId)));field('returnsSales').innerHTML=table(['رقم الفاتورة','التاريخ','الإجمالي','الإجراء'],STORE.sales.slice().reverse().map(s=>'<tr><td>'+s.id+'</td><td>'+new Date(s.date).toLocaleString('ar-LY')+'</td><td>'+money(s.total)+'</td><td>'+(done.has(Number(s.id))?'<b>تم الاسترجاع</b>':'<button class="secondary" onclick="returnSale('+s.id+')">استرجاع</button>')+'</td></tr>'))};

window.backupData=function(){const blob=new Blob([JSON.stringify(STORE,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='omarpos-backup-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.restoreData=function(){modal('<div class="modal-box"><h2>استعادة نسخة احتياطية</h2><p>اختر ملف النسخة الاحتياطية JSON.</p><input id="restoreFile" type="file" accept=".json,application/json"><button class="primary" onclick="doRestore()">استعادة</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>')};
window.doRestore=async function(){const f=field('restoreFile')?.files?.[0];if(!f)return alert('اختر ملفاً.');try{const d=JSON.parse(await f.text());if(!d||!Array.isArray(d.products))throw new Error();await save(shape(d));closeModal();page('home');alert('تمت استعادة البيانات بنجاح.')}catch(e){alert('ملف النسخة الاحتياطية غير صالح.')}};

window.settings=function(){module('الإعدادات والنظام','<div class="section"><h2>إعدادات البرنامج</h2><p>مركز المهندس</p><button class="primary" onclick="backupData()">⬇ تصدير نسخة احتياطية</button><button class="secondary" onclick="restoreData()">⬆ استعادة نسخة احتياطية</button></div>')};
window.showSystemInfo=function(){module('المستخدمون','<div class="section"><h2>المستخدم الحالي</h2><p>اسم المستخدم: <b>'+esc(user)+'</b></p><p>الصلاحية: <b>'+esc(role)+'</b></p></div>')};

const oldPage=window.page;
window.page=function(p){if(p==='home'){if(typeof dashboard==='function')dashboard();else oldPage(p);return}if(p==='customers')return customers();if(p==='settings')return settings();if(p==='sales')return renderSales();return oldPage(p)};
function dashboard(){
 const c=field('content');if(!c)return;field('title').textContent='الرئيسية';
 const card=(cl,ic,t,sub,fn)=>'<button class="dash-card '+cl+'" onclick="'+fn+'"><span>'+ic+'</span><b>'+t+'</b><small>'+sub+'</small></button>';
 c.innerHTML='<div class="dash-group"><h2>المبيعات 🛒</h2><div class="dash-grid">'+card('green','🧾＋','فاتورة مبيعات','إصدار فاتورة جديدة','newInvoice()')+card('green','🛒','المبيعات','عرض الفواتير','page(\\'sales\\')')+card('green','▥','باركود المنتجات','البحث والبيع بالباركود','barcodeProducts()')+card('green','↩','مرتجعات المبيعات','استرجاع الفواتير','salesReturns()')+card('green','🧾','سند قبض','تسجيل مبالغ نقدية','receipts()')+'</div></div>'+
 '<div class="dash-group"><h2>المنتجات والمخزون 📦</h2><div class="dash-grid">'+card('blue','📦','المنتجات','إدارة المنتجات','showProducts()')+card('blue','▦','المخزون','مراقبة الكميات','inventory()')+card('blue','📋','الجرد','جرد المخزون الفعلي','stocktake()')+card('blue','🏪','الموردون','إدارة الموردين','suppliers()')+card('blue','🏷','المشتريات','فواتير المشتريات','purchases()')+'</div></div>'+
 '<div class="dash-group"><h2>العملاء والمالية 👥</h2><div class="dash-grid">'+card('orange','👥','العملاء','إدارة العملاء','customers()')+card('orange','💰','المصروفات','تسجيل المصروفات','expenses()')+card('orange','💳','سند صرف','صرف مبالغ مالية','payments()')+card('orange','🧮','الحسابات','الحسابات المالية','accounts()')+card('orange','📈','الأرباح','الأرباح والخسائر','profits()')+'</div></div>'+
 '<div class="dash-group"><h2>التقارير 📊</h2><div class="dash-grid">'+card('purple','📑','تقرير شامل','تقرير النشاط','page(\\'reports\\')')+card('purple','📦','تقارير المخزون','حركة الأصناف','inventory()')+card('purple','👥','تقارير العملاء','بيانات العملاء','customers()')+card('purple','💰','تقارير الأرباح','ملخص الأرباح','profits()')+card('purple','🧾','تقارير المبيعات','الفواتير','page(\\'sales\\')')+'</div></div>'+
 '<div class="dash-group"><h2>الإعدادات والنظام ⚙</h2><div class="dash-grid">'+card('gray','👤','المستخدمون','إدارة المستخدمين','showSystemInfo()')+card('gray','🛡','النسخ الاحتياطي','حفظ واستعادة البيانات','restoreData()')+card('gray','🔑','تفعيل الاشتراك','إدارة الاشتراك','openActivation()')+card('gray','⚙','الإعدادات','إعدادات البرنامج','settings()')+card('gray','↪','خروج','تسجيل الخروج','logout()')+'</div></div>';
 document.querySelectorAll('nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page==='home'))
}
setTimeout(()=>{if(field('app')&&!field('app').classList.contains('hidden'))dashboard()},300);
})();