(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money2=n=>Number(n||0).toFixed(2)+' د.ل';
async function fresh(){STORE=await window.omarpos.getStore();['products','sales','customers','suppliers','purchases','expenses','payments','receipts','returns','accounts'].forEach(k=>{if(!Array.isArray(STORE[k]))STORE[k]=[]});demoProducts.length=0;STORE.products.forEach(p=>demoProducts.push(p))}
async function save(){await window.omarpos.saveStore(STORE);await fresh()}
function header(title,body){document.getElementById('title').textContent=title;document.getElementById('content').innerHTML=body}
function table(rows,heads,actions){return rows.length?`<table class="table"><thead><tr>${heads.map(h=>'<th>'+h+'</th>').join('')}<th>الإجراء</th></tr></thead><tbody>${rows.map((r,i)=>`<tr>${heads.map(h=>'<td>'+esc(r[h.key]??'')+'</td>').join('')}<td>${actions(r,i)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">لا توجد بيانات.</div>'}
window.showProducts=async function(){await fresh();header('المنتجات والمخزون',`<div class="section"><div class="pos-head"><h2>إدارة المنتجات</h2><button class="primary" onclick="openProductForm()">＋ إضافة صنف جديد</button></div><div id="productTable"></div></div>`);renderP()};
function renderP(){document.getElementById('productTable').innerHTML=demoProducts.length?`<table class="table"><tr><th>الصنف</th><th>الباركود</th><th>السعر</th><th>المخزون</th><th>الإجراء</th></tr>${demoProducts.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.barcode)}</td><td>${money2(p.price)}</td><td>${p.stock}</td><td><button class="secondary" onclick="openProductForm(${p.id})">تعديل</button> <button class="secondary" onclick="deleteProduct(${p.id})">حذف</button></td></tr>`).join('')}</table>`:'<div class="empty">لا توجد أصناف.</div>'}
window.barcodeProducts=async function(){await fresh();header('باركود المنتجات',`<div class="section"><div class="pos-head"><h2>إدارة والبحث بالباركود</h2><button class="primary" onclick="openProductForm()">＋ إضافة صنف</button></div><input id="barcodeQ" autofocus placeholder="امسح الباركود أو اكتبه هنا" style="width:100%;padding:14px;background:#06111a;color:#fff;border:1px solid #15354b;border-radius:9px" oninput="findBarcode()"><div id="barcodeResult" style="margin-top:15px"></div></div>`)};
window.findBarcode=function(){const q=(document.getElementById('barcodeQ')?.value||'').trim();const a=demoProducts.filter(p=>String(p.barcode||'').includes(q));document.getElementById('barcodeResult').innerHTML=q?(a.length?a.map(p=>`<div class="section"><h3>${esc(p.name)}</h3><p>الباركود: ${esc(p.barcode)} | السعر: ${money2(p.price)} | المخزون: ${p.stock}</p><button class="primary" onclick="newInvoiceWithProduct(${p.id})">إضافة للبيع</button></div>`).join(''):'<div class="empty">لم يتم العثور على الصنف.</div>'):''};
window.newInvoiceWithProduct=function(id){newInvoice();setTimeout(()=>addToCart(id),50)};
window.inventory=async function(){await fresh();header('المخزون',`<div class="section"><h2>حالة المخزون</h2>${table(STORE.products,[{key:'name'},{key:'barcode'},{key:'stock'}],()=>'<span>متاح</span>')}</div>`)};
window.stocktake=async function(){await fresh();header('الجرد',`<div class="section"><h2>الجرد الفعلي</h2><table class="table"><tr><th>الصنف</th><th>الحالي</th><th>الفعلي</th><th>حفظ</th></tr>${STORE.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.stock}</td><td><input id="stk${p.id}" type="number" min="0" value="${p.stock}"></td><td><button class="secondary" onclick="saveStock(${p.id})">حفظ</button></td></tr>`).join('')}</table></div>`)};
window.saveStock=async function(id){const p=STORE.products.find(x=>Number(x.id)===Number(id)),v=Number(document.getElementById('stk'+id).value);if(!p||!Number.isInteger(v)||v<0)return alert('الكمية غير صحيحة');p.stock=v;await save();stocktake()};
function crud(title,key,heads,form){header(title,`<div class="section"><div class="pos-head"><h2>${title}</h2><button class="primary" onclick="${form}">＋ إضافة</button></div><div id="crud"></div></div>`);renderCrud(key,heads)}
function renderCrud(k,heads){document.getElementById('crud').innerHTML=table(STORE[k],heads,(r,i)=>`<button class="secondary" onclick="removeCrud('${k}',${i})">حذف</button>`) };
window.removeCrud=async function(k,i){if(!confirm('حذف السجل؟'))return;STORE[k].splice(i,1);await save();renderCrud(k,k==='customers'?[{key:'name'},{key:'phone'},{key:'amount'}]:[{key:'name'},{key:'amount'},{key:'date'}])};
window.customers=async function(){await fresh();crud('العملاء','customers',[{key:'name'},{key:'phone'},{key:'amount'}],'addCustomer()')};
window.addCustomer=async function(){const name=prompt('اسم العميل:');if(!name)return;const phone=prompt('رقم الهاتف:')||'';STORE.customers.push({id:Date.now(),name,phone,amount:0});await save();customers()};
window.suppliers=async function(){await fresh();crud('الموردون','suppliers',[{key:'name'},{key:'phone'},{key:'amount'}],'addSupplier()')};
window.addSupplier=async function(){const name=prompt('اسم المورد:');if(!name)return;const phone=prompt('رقم الهاتف:')||'';STORE.suppliers.push({id:Date.now(),name,phone,amount:0});await save();suppliers()};
window.purchases=async function(){await fresh();header('المشتريات',`<div class="section"><div class="pos-head"><h2>فواتير المشتريات</h2><button class="primary" onclick="addPurchase()">＋ تسجيل مشتريات</button></div><div id="purchaseTable"></div></div>`);document.getElementById('purchaseTable').innerHTML=table(STORE.purchases,[{key:'name'},{key:'amount'},{key:'date'}],(r,i)=>`<button class="secondary" onclick="removeCrud('purchases',${i})">حذف</button>`) };
window.addPurchase=async function(){const name=prompt('اسم الصنف/المورد:');if(!name)return;const amount=Number(prompt('قيمة المشتريات:')||0);if(amount<0)return;STORE.purchases.push({id:Date.now(),name,amount,date:new Date().toISOString()});await save();purchases()};
window.expenses=async function(){await fresh();crud('المصروفات','expenses',[{key:'name'},{key:'amount'},{key:'date'}],'addExpense()')};
window.addExpense=async function(){const name=prompt('بيان المصروف:');if(!name)return;const amount=Number(prompt('المبلغ:')||0);if(amount<0)return;STORE.expenses.push({id:Date.now(),name,amount,date:new Date().toISOString()});await save();expenses()};
window.payments=async function(){await fresh();crud('سند صرف','payments',[{key:'name'},{key:'amount'},{key:'date'}],'addPayment()')};
window.addPayment=async function(){const name=prompt('بيان سند الصرف:');if(!name)return;const amount=Number(prompt('المبلغ:')||0);if(amount<0)return;STORE.payments.push({id:Date.now(),name,amount,date:new Date().toISOString()});await save();payments()};
window.receipts=async function(){await fresh();crud('سند قبض','receipts',[{key:'name'},{key:'amount'},{key:'date'}],'addReceipt()')};
window.addReceipt=async function(){const name=prompt('بيان سند القبض:');if(!name)return;const amount=Number(prompt('المبلغ:')||0);if(amount<0)return;STORE.receipts.push({id:Date.now(),name,amount,date:new Date().toISOString()});await save();receipts()};
window.accounts=async function(){await fresh();const inc=STORE.receipts.reduce((a,x)=>a+Number(x.amount||0),0),out=STORE.payments.reduce((a,x)=>a+Number(x.amount||0),0);header('الحسابات',`<div class="stats"><div class="stat"><b>${money2(inc)}</b><small>سندات القبض</small></div><div class="stat"><b>${money2(out)}</b><small>سندات الصرف</small></div><div class="stat"><b>${money2(inc-out)}</b><small>الرصيد</small></div></div>`)};
window.profits=async function(){await fresh();const sales=STORE.sales.reduce((a,x)=>a+Number(x.total||0),0),expenses=STORE.expenses.reduce((a,x)=>a+Number(x.amount||0),0),purchases=STORE.purchases.reduce((a,x)=>a+Number(x.amount||0),0);header('الأرباح والخسائر',`<div class="stats"><div class="stat"><b>${money2(sales)}</b><small>المبيعات</small></div><div class="stat"><b>${money2(purchases)}</b><small>المشتريات</small></div><div class="stat"><b>${money2(expenses)}</b><small>المصروفات</small></div><div class="stat"><b>${money2(sales-purchases-expenses)}</b><small>الصافي</small></div></div>`)};
window.salesReturns=async function(){await fresh();header('استرجاع المبيعات',`<div class="section"><h2>اختر فاتورة لإرجاعها</h2><div id="returnList"></div></div>`);document.getElementById('returnList').innerHTML=STORE.sales.length?STORE.sales.slice().reverse().map(s=>`<div class="section"><b>فاتورة ${s.id}</b> — ${money2(s.total)}<button class="primary" onclick="returnSale(${s.id})">↩ استرجاع الفاتورة</button></div>`).join(''):'<div class="empty">لا توجد فواتير.</div>'};
window.returnSale=async function(id){const s=STORE.sales.find(x=>Number(x.id)===Number(id));if(!s||!confirm('استرجاع هذه الفاتورة وإعادة المخزون؟'))return;for(const i of s.items||[]){const p=STORE.products.find(x=>Number(x.id)===Number(i.id));if(p)p.stock=Number(p.stock||0)+Number(i.qty||0)}STORE.returns.push({...s,returnedAt:new Date().toISOString()});STORE.sales=STORE.sales.filter(x=>Number(x.id)!==Number(id));await save();salesReturns();alert('تم الاسترجاع وإعادة الكمية للمخزون.')};
})();
