const express=require('express');const helmet=require('helmet');const bcrypt=require('bcryptjs');const Database=require('better-sqlite3');const fs=require('fs');const path=require('path');
const app=express();app.use(helmet());app.use(express.json({limit:'100kb'}));const port=Number(process.env.PORT||8787);const dbFile=path.resolve(process.env.DB_FILE||'./data/licenses.db');fs.mkdirSync(path.dirname(dbFile),{recursive:true});const db=new Database(dbFile);
db.exec(`CREATE TABLE IF NOT EXISTS subscriptions(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,plan TEXT NOT NULL CHECK(plan IN ('7days','monthly','yearly','lifetime')),start_at TEXT NOT NULL,end_at TEXT,status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended')),created_at TEXT NOT NULL,updated_at TEXT NOT NULL);`);
const plans=['7days','monthly','yearly','lifetime'];const now=()=>new Date().toISOString();function publicSub(r){if(!r)return null;const expired=r.end_at?Date.now()>=new Date(r.end_at).getTime():false;return{id:r.id,username:r.username,plan:r.plan,startAt:r.start_at,endAt:r.end_at,status:r.status,expired,active:r.status==='active'&&!expired}}function auth(req,res,next){const h=req.get('authorization')||'';const raw=h.startsWith('Basic ')?Buffer.from(h.slice(6),'base64').toString('utf8'):':';const i=raw.indexOf(':');const u=i>=0?raw.slice(0,i):'',p=i>=0?raw.slice(i+1):'';if(!process.env.ADMIN_USERNAME||!process.env.ADMIN_PASSWORD_HASH||u!==process.env.ADMIN_USERNAME||!bcrypt.compareSync(p,process.env.ADMIN_PASSWORD_HASH)){res.set('WWW-Authenticate','Basic realm="OmarPOS Admin"');return res.status(401).json({error:'unauthorized'})}next()}
app.get('/health',(_req,res)=>res.json({ok:true,service:'omarpos-license-server'}));app.post('/api/auth/login',(req,res)=>{const{username,password}=req.body||{};if(typeof username!=='string'||typeof password!=='string')return res.status(400).json({error:'invalid_request'});const r=db.prepare('SELECT * FROM subscriptions WHERE username=?').get(username.trim());if(!r||!bcrypt.compareSync(password,r.password_hash))return res.status(401).json({error:'invalid_credentials'});res.json({subscription:publicSub(r)})});
app.get('/api/admin/subscriptions',auth,(_req,res)=>res.json(db.prepare('SELECT * FROM subscriptions ORDER BY id DESC').all().map(publicSub)));
app.post('/api/admin/subscriptions',auth,(req,res)=>{const{username,password,plan,startAt,endAt,status}=req.body||{};if(!username||!password||!plans.includes(plan)||!startAt)return res.status(400).json({error:'invalid_request'});const t=now();try{const info=db.prepare('INSERT INTO subscriptions(username,password_hash,plan,start_at,end_at,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(username.trim(),bcrypt.hashSync(password,12),plan,new Date(startAt).toISOString(),endAt?new Date(endAt).toISOString():null,status==='suspended'?'suspended':'active',t,t);res.status(201).json(publicSub(db.prepare('SELECT * FROM subscriptions WHERE id=?').get(info.lastInsertRowid)))}catch(e){res.status(409).json({error:'username_exists'})}});
app.patch('/api/admin/subscriptions/:id',auth,(req,res)=>{const id=Number(req.params.id),r=db.prepare('SELECT * FROM subscriptions WHERE id=?').get(id);if(!r)return res.status(404).json({error:'not_found'});const b=req.body||{},f=[],v=[];if(b.plan!==undefined){if(!plans.includes(b.plan))return res.status(400).json({error:'invalid_plan'});f.push('plan=?');v.push(b.plan)}if(b.startAt!==undefined){f.push('start_at=?');v.push(new Date(b.startAt).toISOString())}if(b.endAt!==undefined){f.push('end_at=?');v.push(b.endAt?new Date(b.endAt).toISOString():null)}if(b.status!==undefined){if(!['active','suspended'].includes(b.status))return res.status(400).json({error:'invalid_status'});f.push('status=?');v.push(b.status)}if(b.password!==undefined){f.push('password_hash=?');v.push(bcrypt.hashSync(String(b.password),12))}if(!f.length)return res.json(publicSub(r));f.push('updated_at=?');v.push(now(),id);db.prepare(`UPDATE subscriptions SET ${f.join(',')} WHERE id=?`).run(...v);res.json(publicSub(db.prepare('SELECT * FROM subscriptions WHERE id=?').get(id)))});
app.delete('/api/admin/subscriptions/:id',auth,(req,res)=>{const x=db.prepare('DELETE FROM subscriptions WHERE id=?').run(Number(req.params.id));if(!x.changes)return res.status(404).json({error:'not_found'});res.status(204).end()});app.listen(port,()=>console.log(`OmarPOS license server listening on :${port}`));
