const express=require('express');const helmet=require('helmet');const bcrypt=require('bcryptjs');const cors=require('cors');const crypto=require('crypto');const path=require('path');const {Pool}=require('pg');
const app=express();app.use(helmet());app.use(cors({origin:process.env.CORS_ORIGIN||true,methods:['GET','POST','PATCH','DELETE'],allowedHeaders:['Content-Type','Authorization'],credentials:true}));app.use(express.json({limit:'100kb'}));
const port=Number(process.env.PORT||8787);if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is required');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='false'?false:{rejectUnauthorized:false},max:10});
const plans=['7days','monthly','yearly','lifetime'];const now=()=>new Date().toISOString();
const adminUsername=(process.env.ADMIN_USERNAME||'admin').trim();const adminPassword=process.env.ADMIN_PASSWORD||'';const adminPasswordHash=process.env.ADMIN_PASSWORD_HASH||'';
const adminSessionKey=crypto.createHash('sha256').update(`${adminUsername}:${adminPasswordHash||adminPassword}`).digest();
function passwordOk(p){if(typeof p!=='string')return false;if(adminPassword)return p===adminPassword;if(adminPasswordHash){try{return bcrypt.compareSync(p,adminPasswordHash)}catch{return false}}return false}
function makeAdminToken(username){const payload=`${username}|${Date.now()}`;const sig=crypto.createHmac('sha256',adminSessionKey).update(payload).digest('base64url');return Buffer.from(`${payload}|${sig}`).toString('base64url')}
function validAdminToken(token){try{const raw=Buffer.from(token,'base64url').toString('utf8');const parts=raw.split('|');if(parts.length!==3)return false;const[u,ts,sig]=parts;const payload=`${u}|${ts}`;const expected=crypto.createHmac('sha256',adminSessionKey).update(payload).digest('base64url');if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return false;if(u!==adminUsername)return false;const t=Number(ts);return Number.isFinite(t)&&Date.now()-t<12*60*60*1000}catch{return false}}
function cookies(req){const out={};for(const part of(req.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS subscriptions(id SERIAL PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,plan TEXT NOT NULL CHECK(plan IN ('7days','monthly','yearly','lifetime')),start_at TIMESTAMPTZ NOT NULL,end_at TIMESTAMPTZ,status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended')),created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL)`)}
function publicSub(r){if(!r)return null;const expired=r.end_at?Date.now()>=new Date(r.end_at).getTime():false;return{id:r.id,username:r.username,plan:r.plan,startAt:r.start_at,endAt:r.end_at,status:r.status,expired,active:r.status==='active'&&!expired}}
function auth(req,res,next){const c=cookies(req);const bearer=(req.get('authorization')||'').startsWith('Bearer ')?req.get('authorization').slice(7).trim():'';if((c.omarpos_admin&&validAdminToken(c.omarpos_admin))||(bearer&&validAdminToken(bearer)))return next();const h=req.get('authorization')||'';let raw=':';try{if(h.startsWith('Basic '))raw=Buffer.from(h.slice(6),'base64').toString('utf8')}catch{}const i=raw.indexOf(':');const u=i>=0?raw.slice(0,i):'',p=i>=0?raw.slice(i+1):'';if(u!==adminUsername||!passwordOk(p)){res.set('WWW-Authenticate','Basic realm="OmarPOS Admin"');return res.status(401).json({error:'unauthorized'})}next()}
app.get('/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,service:'omarpos-license-server'})}catch{res.status(503).json({ok:false})}});
app.get('/admin',(_req,res)=>{res.set('Cache-Control','no-store');res.sendFile(path.join(__dirname,'admin.html'))});app.get('/admin.js',(_req,res)=>{res.set('Cache-Control','no-store');res.sendFile(path.join(__dirname,'admin.js'))});app.get('/admin.css',(_req,res)=>{res.set('Cache-Control','no-store');res.sendFile(path.join(__dirname,'admin.css'))});
app.post('/api/admin/login',(req,res)=>{const{username,password}=req.body||{};if(typeof username!=='string'||typeof password!=='string')return res.status(400).json({error:'invalid_request'});if(username.trim()!==adminUsername||!passwordOk(password))return res.status(401).json({error:'unauthorized'});const token=makeAdminToken(adminUsername);res.set('Set-Cookie',`omarpos_admin=${token}; Path=/; Max-Age=43200; HttpOnly; SameSite=Lax`);res.json({ok:true,token})});
app.post('/api/admin/logout',(_req,res)=>{res.set('Set-Cookie','omarpos_admin=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax');res.json({ok:true})});
app.post('/api/auth/login',async(req,res)=>{const{username,password}=req.body||{};if(typeof username!=='string'||typeof password!=='string')return res.status(400).json({error:'invalid_request'});try{const q=await pool.query('SELECT * FROM subscriptions WHERE username=$1',[username.trim()]);const r=q.rows[0];if(!r||!bcrypt.compareSync(password,r.password_hash))return res.status(401).json({error:'invalid_credentials'});res.json({subscription:publicSub(r)})}catch(e){console.error(e);res.status(500).json({error:'server_error'})}});
app.get('/api/admin/subscriptions',auth,async(_req,res)=>{try{const q=await pool.query('SELECT * FROM subscriptions ORDER BY id DESC');res.json(q.rows.map(publicSub))}catch(e){console.error(e);res.status(500).json({error:'server_error'})}});
app.post('/api/admin/subscriptions',auth,async(req,res)=>{const{username,password,plan,startAt,endAt,status}=req.body||{};if(!username||typeof password!=='string'||password.length<4||!plans.includes(plan)||!startAt)return res.status(400).json({error:'invalid_request'});try{const start=new Date(startAt);const end=endAt?new Date(endAt):null;if(Number.isNaN(start.getTime())||(end&&Number.isNaN(end.getTime())))return res.status(400).json({error:'invalid_date'});if(end&&end<start)return res.status(400).json({error:'invalid_date_range'});const q=await pool.query('INSERT INTO subscriptions(username,password_hash,plan,start_at,end_at,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[username.trim(),bcrypt.hashSync(password,12),plan,start,end,status==='suspended'?'suspended':'active',now()]);res.status(201).json(publicSub(q.rows[0]))}catch(e){console.error('Create subscription failed:',e);if(e.code==='23505')return res.status(409).json({error:'username_exists'});res.status(500).json({error:e.code||'unknown_db_error'})}});
app.patch('/api/admin/subscriptions/:id',auth,async(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({error:'invalid_id'});const b=req.body||{},f=[],v=[];if(b.plan!==undefined){if(!plans.includes(b.plan))return res.status(400).json({error:'invalid_plan'});f.push('plan=$'+(v.length+1));v.push(b.plan)}if(b.startAt!==undefined){const d=new Date(b.startAt);if(Number.isNaN(d.getTime()))return res.status(400).json({error:'invalid_date'});f.push('start_at=$'+(v.length+1));v.push(d)}if(b.endAt!==undefined){if(b.endAt){const d=new Date(b.endAt);if(Number.isNaN(d.getTime()))return res.status(400).json({error:'invalid_date'});f.push('end_at=$'+(v.length+1));v.push(d)}else{f.push('end_at=$'+(v.length+1));v.push(null)}}if(b.status!==undefined){if(!['active','suspended'].includes(b.status))return res.status(400).json({error:'invalid_status'});f.push('status=$'+(v.length+1));v.push(b.status)}if(b.password!==undefined){if(String(b.password).length<4)return res.status(400).json({error:'weak_password'});f.push('password_hash=$'+(v.length+1));v.push(bcrypt.hashSync(String(b.password),12))}if(!f.length){const q=await pool.query('SELECT * FROM subscriptions WHERE id=$1',[id]);return q.rows[0]?res.json(publicSub(q.rows[0])):res.status(404).json({error:'not_found'})}f.push('updated_at=$'+(v.length+1));v.push(now());v.push(id);try{const q=await pool.query(`UPDATE subscriptions SET ${f.join(',')} WHERE id=$${v.length} RETURNING *`,v);if(!q.rows[0])return res.status(404).json({error:'not_found'});return res.json(publicSub(q.rows[0]))}catch(e){console.error(e);res.status(500).json({error:e.code||'unknown_db_error'})}});
app.delete('/api/admin/subscriptions/:id',auth,async(req,res)=>{try{const q=await pool.query('DELETE FROM subscriptions WHERE id=$1',[Number(req.params.id)]);if(!q.rowCount)return res.status(404).json({error:'not_found'});res.status(204).end()}catch(e){console.error(e);res.status(500).json({error:e.code||'unknown_db_error'})}});
init().then(()=>app.listen(port,'0.0.0.0',()=>console.log(`OmarPOS license server listening on :${port}`))).catch(e=>{console.error('Database initialization failed',e);process.exit(1)});process.on('SIGTERM',async()=>{await pool.end();process.exit(0)});